local DF = LibStub('AceAddon-3.0'):GetAddon('DragonflightUI')

local locale = GetLocale()

function DragonflightUILocalizationData:Getss()
    print('GETSSssss')
end

-- Professions

local ProfessionNamesToSkillID = {}

-- https://github.com/tekkub/wow-globalstrings/blob/master/GlueStrings/deDE.lua
if locale == 'deDE' then
    CHARACTER_PROFESSION_ALCHEMY = "Alchemie";
    CHARACTER_PROFESSION_BLACKSMITHING = "Schmiedekunst";
    CHARACTER_PROFESSION_ENCHANTING = "Verzauberkunst";
    CHARACTER_PROFESSION_ENGINEERING = "Ingenieurskunst";
    CHARACTER_PROFESSION_FIRST_AID = "Erste Hilfe";
    CHARACTER_PROFESSION_HERBALISM = "Kräuterkunde";
    CHARACTER_PROFESSION_INSCRIPTION = "Inschriftenkunde";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Juwelierskunst";
    CHARACTER_PROFESSION_LEATHERWORKING = "Lederverarbeitung";
    CHARACTER_PROFESSION_MINING = "Bergbau";
    CHARACTER_PROFESSION_SKINNING = "Kürschnerei";
    CHARACTER_PROFESSION_TAILORING = "Schneiderei";

    PROFESSIONS_COOKING = "Kochkunst";
    PROFESSIONS_FISHING = "Angeln";

    PROFESSIONS_POISON = "Gifte"
    PROFESSIONS_BEAST = "Wildtierausbildung"
elseif locale == 'enUS' then
    CHARACTER_PROFESSION_ALCHEMY = "Alchemy";
    CHARACTER_PROFESSION_BLACKSMITHING = "Blacksmithing";
    CHARACTER_PROFESSION_ENCHANTING = "Enchanting";
    CHARACTER_PROFESSION_ENGINEERING = "Engineering";
    CHARACTER_PROFESSION_FIRST_AID = "First Aid";
    CHARACTER_PROFESSION_HERBALISM = "Herbalism";
    CHARACTER_PROFESSION_INSCRIPTION = "Inscription";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Jewelcrafting";
    CHARACTER_PROFESSION_LEATHERWORKING = "Leatherworking";
    CHARACTER_PROFESSION_MINING = "Mining";
    CHARACTER_PROFESSION_SKINNING = "Skinning";
    CHARACTER_PROFESSION_TAILORING = "Tailoring";

    PROFESSIONS_COOKING = "Cooking";
    PROFESSIONS_FISHING = "Fishing";

    PROFESSIONS_POISON = "Poisons"
    PROFESSIONS_BEAST = "Beast Training"
elseif locale == 'esMX' or locale == 'esES' then
    CHARACTER_PROFESSION_ALCHEMY = "Alquimia";
    CHARACTER_PROFESSION_BLACKSMITHING = "Herrería";
    CHARACTER_PROFESSION_ENCHANTING = "Encantamiento";
    CHARACTER_PROFESSION_ENGINEERING = "Ingeniería";
    CHARACTER_PROFESSION_FIRST_AID = "Primeros auxilios";
    CHARACTER_PROFESSION_HERBALISM = "Herboristería";
    CHARACTER_PROFESSION_INSCRIPTION = "Inscripción";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Joyería";
    CHARACTER_PROFESSION_LEATHERWORKING = "Peletería";
    CHARACTER_PROFESSION_MINING = "Minería";
    CHARACTER_PROFESSION_SKINNING = "Desuello";
    CHARACTER_PROFESSION_TAILORING = "Sastrería";

    PROFESSIONS_COOKING = "Cocina";
    PROFESSIONS_FISHING = "Pesca";

    PROFESSIONS_POISON = "Venenos"
    PROFESSIONS_BEAST = "Doma de bestias"
elseif locale == 'frFR' then
    CHARACTER_PROFESSION_ALCHEMY = "Alchimie";
    CHARACTER_PROFESSION_BLACKSMITHING = "Forge";
    CHARACTER_PROFESSION_ENCHANTING = "Enchantement";
    CHARACTER_PROFESSION_ENGINEERING = "Ingénierie";
    CHARACTER_PROFESSION_FIRST_AID = "Secourisme";
    CHARACTER_PROFESSION_HERBALISM = "Herboristerie";
    CHARACTER_PROFESSION_INSCRIPTION = "Calligraphie";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Joaillerie";
    CHARACTER_PROFESSION_LEATHERWORKING = "Travail du cuir";
    CHARACTER_PROFESSION_MINING = "Minage";
    CHARACTER_PROFESSION_SKINNING = "Dépeçage";
    CHARACTER_PROFESSION_TAILORING = "Couture";

    PROFESSIONS_COOKING = "Cuisine";
    PROFESSIONS_FISHING = "Pêche";

    PROFESSIONS_POISON = "Poisons"
    PROFESSIONS_BEAST = "Dressage des bêtes"
elseif locale == 'itIT' then
    CHARACTER_PROFESSION_ALCHEMY = "Alchimia";
    CHARACTER_PROFESSION_BLACKSMITHING = "Forgiatura";
    CHARACTER_PROFESSION_ENCHANTING = "Incantamento";
    CHARACTER_PROFESSION_ENGINEERING = "Ingegneria";
    CHARACTER_PROFESSION_FIRST_AID = "Primo Soccorso";
    CHARACTER_PROFESSION_HERBALISM = "Erbalismo";
    CHARACTER_PROFESSION_INSCRIPTION = "Runografia";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Oreficeria";
    CHARACTER_PROFESSION_LEATHERWORKING = "Conciatura";
    CHARACTER_PROFESSION_MINING = "Estrazione";
    CHARACTER_PROFESSION_SKINNING = "Scuoiatura";
    CHARACTER_PROFESSION_TAILORING = "Sartoria";

    PROFESSIONS_COOKING = "Cucina";
    PROFESSIONS_FISHING = "Pesca";

    PROFESSIONS_POISON = "Poisons"
    PROFESSIONS_BEAST = "Beast Training"
elseif locale == 'koKR' then
    CHARACTER_PROFESSION_ALCHEMY = "연금술";
    CHARACTER_PROFESSION_BLACKSMITHING = "대장기술";
    CHARACTER_PROFESSION_ENCHANTING = "마법부여";
    CHARACTER_PROFESSION_ENGINEERING = "기계공학";
    CHARACTER_PROFESSION_FIRST_AID = "응급치료";
    CHARACTER_PROFESSION_HERBALISM = "약초채집";
    CHARACTER_PROFESSION_INSCRIPTION = "주문각인";
    CHARACTER_PROFESSION_JEWELCRAFTING = "보석세공";
    CHARACTER_PROFESSION_LEATHERWORKING = "가죽세공";
    CHARACTER_PROFESSION_MINING = "채광";
    CHARACTER_PROFESSION_SKINNING = "무두질";
    CHARACTER_PROFESSION_TAILORING = "재봉술";

    PROFESSIONS_COOKING = "요리";
    PROFESSIONS_FISHING = "낚시";

    PROFESSIONS_POISON = "독 조제"
    PROFESSIONS_BEAST = "야수 조련"
elseif locale == 'ptBR' then
    CHARACTER_PROFESSION_ALCHEMY = "Alquimia";
    CHARACTER_PROFESSION_BLACKSMITHING = "Ferraria";
    CHARACTER_PROFESSION_ENCHANTING = "Encantamento";
    CHARACTER_PROFESSION_ENGINEERING = "Engenharia";
    CHARACTER_PROFESSION_FIRST_AID = "Primeiros Socorros";
    CHARACTER_PROFESSION_HERBALISM = "Herborismo";
    CHARACTER_PROFESSION_INSCRIPTION = "Escrivania";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Joalheria";
    CHARACTER_PROFESSION_LEATHERWORKING = "Couraria";
    CHARACTER_PROFESSION_MINING = "Mineração";
    CHARACTER_PROFESSION_SKINNING = "Esfolamento";
    CHARACTER_PROFESSION_TAILORING = "Alfaiataria";

    PROFESSIONS_COOKING = "Culinária";
    PROFESSIONS_FISHING = "Pesca";

    PROFESSIONS_POISON = "Venenos"
    PROFESSIONS_BEAST = "Treinamento de Feras"
elseif locale == 'ruRU' then
    CHARACTER_PROFESSION_ALCHEMY = "Алхимия";
    CHARACTER_PROFESSION_BLACKSMITHING = "Кузнечное дело";
    CHARACTER_PROFESSION_ENCHANTING = "Наложение чар";
    CHARACTER_PROFESSION_ENGINEERING = "Инженерное дело";
    CHARACTER_PROFESSION_FIRST_AID = "Первая помощь";
    CHARACTER_PROFESSION_HERBALISM = "Травничество";
    CHARACTER_PROFESSION_INSCRIPTION = "Начертание";
    CHARACTER_PROFESSION_JEWELCRAFTING = "Ювелирное дело";
    CHARACTER_PROFESSION_LEATHERWORKING = "Кожевничество";
    CHARACTER_PROFESSION_MINING = "Горное дело";
    CHARACTER_PROFESSION_SKINNING = "Снятие шкур";
    CHARACTER_PROFESSION_TAILORING = "Портняжное дело";

    PROFESSIONS_COOKING = "Кулинария";
    PROFESSIONS_FISHING = "Рыбная ловля";

    PROFESSIONS_POISON = "Яды"
    PROFESSIONS_BEAST = "Дрессировка"
elseif locale == 'zhCN' then
    CHARACTER_PROFESSION_ALCHEMY = "炼金术";
    CHARACTER_PROFESSION_BLACKSMITHING = "锻造";
    CHARACTER_PROFESSION_ENCHANTING = "附魔";
    CHARACTER_PROFESSION_ENGINEERING = "工程学";
    CHARACTER_PROFESSION_FIRST_AID = "急救";
    CHARACTER_PROFESSION_HERBALISM = "草药学";
    CHARACTER_PROFESSION_INSCRIPTION = "铭文";
    CHARACTER_PROFESSION_JEWELCRAFTING = "珠宝加工";
    CHARACTER_PROFESSION_LEATHERWORKING = "制皮";
    CHARACTER_PROFESSION_MINING = "采矿";
    CHARACTER_PROFESSION_SKINNING = "剥皮";
    CHARACTER_PROFESSION_TAILORING = "裁缝";

    PROFESSIONS_COOKING = "烹饪";
    PROFESSIONS_FISHING = "钓鱼";

    PROFESSIONS_POISON = "毒药"
    PROFESSIONS_BEAST = "训练野兽"
elseif locale == 'zhTW' then
    CHARACTER_PROFESSION_ALCHEMY = "鍊金術";
    CHARACTER_PROFESSION_BLACKSMITHING = "鍛造";
    CHARACTER_PROFESSION_ENCHANTING = "附魔";
    CHARACTER_PROFESSION_ENGINEERING = "工程學";
    CHARACTER_PROFESSION_FIRST_AID = "急救";
    CHARACTER_PROFESSION_HERBALISM = "草藥學";
    CHARACTER_PROFESSION_INSCRIPTION = "銘文";
    CHARACTER_PROFESSION_JEWELCRAFTING = "珠寶設計";
    CHARACTER_PROFESSION_LEATHERWORKING = "製皮";
    CHARACTER_PROFESSION_MINING = "採礦";
    CHARACTER_PROFESSION_SKINNING = "剝皮";
    CHARACTER_PROFESSION_TAILORING = "裁縫";

    PROFESSIONS_COOKING = "烹飪";
    PROFESSIONS_FISHING = "釣魚";

    PROFESSIONS_POISON = "毒藥"
    PROFESSIONS_BEAST = "訓練野獸"
end

--[[ First Aid 	129										
Blacksmithing	164	
Leatherworking	165	
Alchemy	171	
Herbalism	182
Cooking	185	
Mining	186
Tailoring	197	
Engineering	202	
Enchanting	333	
Fishing	356
Skinning	393	
Jewelcrafting 	755
Inscription 	773	
Archeology 	794
 ]]

ProfessionNamesToSkillID[CHARACTER_PROFESSION_ALCHEMY] = 171
ProfessionNamesToSkillID[CHARACTER_PROFESSION_BLACKSMITHING] = 164
ProfessionNamesToSkillID[CHARACTER_PROFESSION_ENCHANTING] = 333
ProfessionNamesToSkillID[CHARACTER_PROFESSION_ENGINEERING] = 202
ProfessionNamesToSkillID[CHARACTER_PROFESSION_FIRST_AID] = 129
ProfessionNamesToSkillID[CHARACTER_PROFESSION_HERBALISM] = 182
ProfessionNamesToSkillID[CHARACTER_PROFESSION_INSCRIPTION] = 773
ProfessionNamesToSkillID[CHARACTER_PROFESSION_JEWELCRAFTING] = 755
ProfessionNamesToSkillID[CHARACTER_PROFESSION_LEATHERWORKING] = 165
ProfessionNamesToSkillID[CHARACTER_PROFESSION_MINING] = 186
ProfessionNamesToSkillID[CHARACTER_PROFESSION_SKINNING] = 393
ProfessionNamesToSkillID[CHARACTER_PROFESSION_TAILORING] = 197

ProfessionNamesToSkillID[PROFESSIONS_COOKING] = 185
ProfessionNamesToSkillID[PROFESSIONS_FISHING] = 356

ProfessionNamesToSkillID[PROFESSIONS_POISON] = 666 -- custom
ProfessionNamesToSkillID[PROFESSIONS_BEAST] = 667 -- custom

function DragonflightUILocalizationData:GetSkillIDFromProfessionName(name)
    return ProfessionNamesToSkillID[name]
end

